class PhilippineLocations {
  static const List<String> regions = [
    'NCR - National Capital Region',
    'CAR - Cordillera Administrative Region',
    'Region I - Ilocos Region',
    'Region II - Cagayan Valley',
    'Region III - Central Luzon',
    'Region IV-A - CALABARZON',
    'Region IV-B - MIMAROPA',
    'Region V - Bicol Region',
    'Region VI - Western Visayas',
    'Region VII - Central Visayas',
    'Region VIII - Eastern Visayas',
    'Region IX - Zamboanga Peninsula',
    'Region X - Northern Mindanao',
    'Region XI - Davao Region',
    'Region XII - SOCCSKSARGEN',
    'Region XIII - Caraga',
    'BARMM - Bangsamoro Autonomous Region in Muslim Mindanao',
  ];

  static const Map<String, List<String>> provinces = {
    'NCR - National Capital Region': ['Metro Manila'],
    'CAR - Cordillera Administrative Region': [
      'Abra',
      'Apayao',
      'Benguet',
      'Ifugao',
      'Kalinga',
      'Mountain Province',
    ],
    'Region I - Ilocos Region': [
      'Ilocos Norte',
      'Ilocos Sur',
      'La Union',
      'Pangasinan',
    ],
    'Region II - Cagayan Valley': [
      'Batanes',
      'Cagayan',
      'Isabela',
      'Nueva Vizcaya',
      'Quirino',
    ],
    'Region III - Central Luzon': [
      'Aurora',
      'Bataan',
      'Bulacan',
      'Nueva Ecija',
      'Pampanga',
      'Tarlac',
      'Zambales',
    ],
    'Region IV-A - CALABARZON': [
      'Batangas',
      'Cavite',
      'Laguna',
      'Quezon',
      'Rizal',
    ],
    'Region IV-B - MIMAROPA': [
      'Marinduque',
      'Occidental Mindoro',
      'Oriental Mindoro',
      'Palawan',
      'Romblon',
    ],
    'Region V - Bicol Region': [
      'Albay',
      'Camarines Norte',
      'Camarines Sur',
      'Catanduanes',
      'Masbate',
      'Sorsogon',
    ],
    'Region VI - Western Visayas': [
      'Aklan',
      'Antique',
      'Capiz',
      'Guimaras',
      'Iloilo',
      'Negros Occidental',
    ],
    'Region VII - Central Visayas': [
      'Bohol',
      'Cebu',
      'Negros Oriental',
      'Siquijor',
    ],
    'Region VIII - Eastern Visayas': [
      'Biliran',
      'Eastern Samar',
      'Leyte',
      'Northern Samar',
      'Samar',
      'Southern Leyte',
    ],
    'Region IX - Zamboanga Peninsula': [
      'Zamboanga del Norte',
      'Zamboanga del Sur',
      'Zamboanga Sibugay',
    ],
    'Region X - Northern Mindanao': [
      'Bukidnon',
      'Camiguin',
      'Lanao del Norte',
      'Misamis Occidental',
      'Misamis Oriental',
    ],
    'Region XI - Davao Region': [
      'Davao de Oro',
      'Davao del Norte',
      'Davao del Sur',
      'Davao Occidental',
      'Davao Oriental',
    ],
    'Region XII - SOCCSKSARGEN': [
      'Cotabato',
      'Sarangani',
      'South Cotabato',
      'Sultan Kudarat',
    ],
    'Region XIII - Caraga': [
      'Agusan del Norte',
      'Agusan del Sur',
      'Dinagat Islands',
      'Surigao del Norte',
      'Surigao del Sur',
    ],
    'BARMM - Bangsamoro Autonomous Region in Muslim Mindanao': [
      'Basilan',
      'Lanao del Sur',
      'Maguindanao',
      'Sulu',
      'Tawi-Tawi',
    ],
  };

  static const Map<String, List<String>> cities = {
    // Laguna cities
    'Laguna': [
      'Biñan',
      'Cabuyao',
      'Calamba',
      'San Pablo',
      'San Pedro',
      'Santa Rosa',
      'Alaminos',
      'Bay',
      'Calauan',
      'Cavinti',
      'Famy',
      'Kalayaan',
      'Liliw',
      'Los Baños',
      'Luisiana',
      'Lumban',
      'Mabitac',
      'Magdalena',
      'Majayjay',
      'Nagcarlan',
      'Paete',
      'Pagsanjan',
      'Pakil',
      'Pangil',
      'Pila',
      'Rizal',
      'San Pedro',
      'Santa Cruz',
      'Santa Maria',
      'Siniloan',
      'Victoria',
    ],
    // Cavite cities
    'Cavite': [
      'Bacoor',
      'Cavite City',
      'Dasmariñas',
      'General Trias',
      'Imus',
      'Tagaytay',
      'Trece Martires',
      'Alfonso',
      'Amadeo',
      'Carmona',
      'General Emilio Aguinaldo',
      'General Mariano Alvarez',
      'Indang',
      'Kawit',
      'Magallanes',
      'Maragondon',
      'Mendez',
      'Naic',
      'Noveleta',
      'Rosario',
      'Silang',
      'Tanza',
      'Ternate',
    ],
    // Metro Manila cities
    'Metro Manila': [
      'Caloocan',
      'Las Piñas',
      'Makati',
      'Malabon',
      'Mandaluyong',
      'Manila',
      'Marikina',
      'Muntinlupa',
      'Navotas',
      'Parañaque',
      'Pasay',
      'Pasig',
      'Quezon City',
      'San Juan',
      'Taguig',
      'Valenzuela',
      'Pateros',
    ],
    // Add more provinces and their cities as needed
  };

  static const Map<String, List<String>> barangays = {
    // Cabuyao, Laguna barangays
    'Cabuyao': [
      'Baclaran',
      'Banay-banay',
      'Banlic',
      'Bigaa',
      'Butong',
      'Casile',
      'Diezmo',
      'Gulod',
      'Mamatid',
      'Marinig',
      'Niugan',
      'Pittland',
      'Pulo',
      'Sala',
      'San Isidro',
      'Barangay Uno',
      'Barangay Dos',
      'Barangay Tres',
    ],
    // Santa Rosa, Laguna barangays
    'Santa Rosa': [
      'Aplaya',
      'Balibago',
      'Caingin',
      'Dila',
      'Dita',
      'Don Jose',
      'Ibaba',
      'Kanluran',
      'Labas',
      'Macabling',
      'Malitlit',
      'Malusak',
      'Market Area',
      'Pooc',
      'Pulong Santa Cruz',
      'Santo Domingo',
      'Sinalhan',
      'Tagapo',
    ],
    // Add more cities and their barangays as needed
  };

  static List<String> getProvinces(String region) {
    return provinces[region] ?? [];
  }

  static List<String> getCities(String province) {
    return cities[province] ?? [];
  }

  static List<String> getBarangays(String city) {
    return barangays[city] ?? [];
  }
}
